# Generated by Django 3.2.23 on 2023-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=45)),
                ('desc', models.CharField(max_length=45)),
                ('post_date', models.DateTimeField()),
                ('location', models.CharField(max_length=45)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('job_nature', models.CharField(max_length=45)),
                ('salary', models.CharField(max_length=45)),
                ('appli_date', models.DateTimeField()),
                ('skills', models.CharField(max_length=300)),
                ('education', models.CharField(max_length=300)),
                ('experience', models.IntegerField()),
                ('company_id', models.IntegerField()),
            ],
            options={
                'db_table': 'job',
                'managed': False,
            },
        ),
    ]
